# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb4359858cce8e069409d9927a1cae5a27f6494563d3b685c7f9858bb9c6e00f102853f174cf39844f2615ce570d72e350d8817732f47cd24658914718d3369

test:
  secret_key_base: 0808d911abd3f516504d4a9de11aa3e7fdeacba7a91fd54756b9d50606def02acdb701917d55242021b438d2fc11298ee96eea7b68f2e1966ee7bb7f22c6e43b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
